name: Build Latest

on: [push,workflow_dispatch]

env:
  DOTNET_SDK_VERSION: '8.0.*'

jobs:
          
  build-mac-x64-arm64:
    
    runs-on: macOS-latest
    
    steps:
      
      - uses: actions/checkout@v1
      
      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - run: dotnet publish BBDown -r osx-arm64 -c Release -o artifact-arm64
      - run: dotnet publish BBDown -r osx-x64 -c Release -o artifact-x64

      
      - name: Upload Artifact[osx-x64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BBDown_osx-x64
          path: artifact-x64/BBDown
  
